### ISSUE TITLE
Bump version & update the wiki to include B2 compatibility

### ISSUE THREAD

**Issue by yourfriendoss** [cloudydeno/deno-aws_api#36]
Usage (for B2) looks something like this:
```
import { ApiFactory } from "https://raw.githubusercontent.com/cloudydeno/deno-aws_api/666991bff325933f28954bc4878fca6aff2f89a1/lib/client/mod.ts";
import { S3 } from "https://aws-api.deno.dev/v0.3/services/s3.ts";

export const minio = new ApiFactory({
  credentials: {
    awsAccessKeyId: Deno.env.get("S3_ACCESS_KEY_ID")!,
    awsSecretKey: Deno.env.get("S3_SECRET_KEY")!,
  },
  fixedEndpoint: "https://s3.us-west-004.backblazeb2.com",
  region: "us-west-004",
}).makeNew(S3);
```

Currently, there's no version that includes fixed B2 support. The version should be probably bumped..?

**Comment by danopia** [comment]
Hi, I just tagged `v0.7.0`. I got distracted in release trying to include #31 and also test Cloudflare R2. So the managed upload stuff will have to wait for the next release.

I've updated https://github.com/cloudydeno/deno-aws_api/wiki/S3-Compatible-Vendors with your report. Thanks again for writing in.
