### ISSUE TITLE
URL in example is incorrect

### ISSUE THREAD

**Issue by GJZwiers** [cloudydeno/deno-aws_api#39]
In the first example in the readme, the path to import one of the URLs is incorrect:

`import { STS } from 'https://deno.land/x/aws_api/services/sts.ts';` results in 404 Not Found.

The URL should instead be: `https://deno.land/x/aws_api/services/sts/mod.ts`

**Comment by danopia** [comment]
Thanks for reporting this, I must've missed this when I restructured the `services/` directory!
